version: "3"
networks:
  php-pg-nginx:

services:
  app:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
    depends_on:
      - fpm
      - postgresql
    networks:
      - php-pg-nginx
  fpm:
    container_name: php-fpm
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www
    networks:
      - php-pg-nginx
  postgresql:
    container_name: postgres
    image: postgres:latest
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./docker/pgsql:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0375Ihor_
      POSTGRES_DB: book_web
    networks:
      - php-pg-nginx
    ports:
      - "5433:5432"
  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./:/var/www
    working_dir: /var/www
volumes:
  pg_data: