version: "3"
networks:
  php-pg-nginx:

services:
  app:
    container_name: nginx
    image: nginx:lastest
    restart: always
    ports:
      - "8000:80"
    working_dir: /var/www/nginx/micro-framework
    volumes:
      - ./logs:/var/log/nginx/micrame
      - ./docker/nginx:/etc/nginx/conf.d
      - .:/var/www/nginx/micro-framework
    depends_on:
      - fpm
      - postgresql
    networks:
      - php-pg-nginx
  fpm:
    container_name: php-fpm
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    working_dir: /var/www/nginx/micro-framework
    volumes:
      - .:/var/www/nginx/micro-framework
    networks:
      - php-pg-nginx
  postgresql:
    container_name: postgres
    image: postgres:latest
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./docker/pgsql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - php-pg-nginx
    ports:
      - "5433:5432"
    env_file:
      - .env
  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./:/var/www/nginx/micro-framework
    working_dir: /var/www/nginx/micro-framework
volumes:
  pg_data: