version: "3"
networks:
  php-pg-nginx:

services:
  fpm:
    container_name: php-fpm
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./logs/php:/usr/local/php-logs
    networks:
      - php-pg-nginx
    restart: unless-stopped
  app:
    container_name: nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "8000:80"
    working_dir: /var/www
    volumes:
      - ./logs/nginx:/var/log/nginx/micrame
      - ./views/assets:/var/www/assets
    depends_on:
      - fpm
      - postgresql
    networks:
      - php-pg-nginx
  postgresql:
    container_name: postgres
    image: postgres:15-alpine
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./docker/postgres/pgsql.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - php-pg-nginx
    ports:
      - "5432:5432"
    env_file:
      - .env
volumes:
  pg_data: